sensitive_words = {
    # Bạo lực, chết chóc
    'c.h.ế.t': 'chết',
    'g.i.ế.t': 'giết',
    'c.h.ế.m': 'chém',
    'c.h.é.m': 'chém',
    'đ.á.n.h': 'đánh',
    'đ.ấ.m': 'đấm',
    'b.ắ.n': 'bắn',
    't.á.t': 'tát',
    't.r.ó.i': 'trói',
    'b.ó.p': 'bóp',
    'b.ó': 'bó',
    'đ.ố.t': 'đốt',
    'p.h.á': 'phá',
    'n.ổ': 'nổ',
    'b.o.m': 'bom',
    'm.í.n': 'mìn',
    't.ự.t.ử': 'tự tử',
    't.ự.s.á.t': 'tự sát',
    't.ử.v.o.n.g': 'tử vong',
    't.r.ầ.m.c.ả.m': 'trầm cảm',
    't.r.ầ.m.u.ấ.t': 'trầm uất',
    't.ự.v.ậ.n': 'tự vận',
    # Tội phạm, tệ nạn
    't.r.ộ.m': 'trộm',
    'c.ắ.p': 'cắp',
    'l.ừ.a': 'lừa',
    'l.ừ.a.đ.ả.o': 'lừa đảo',
    'g.i.ả.m.đ.ị.n.h': 'giảm định',
    'c.ư.ớ.p': 'cướp',
    'g.i.ậ.t': 'giật',
    'h.i.ế.p': 'hiếp',
    'b.ắ.t.c.ó.c': 'bắt cóc',
    'm.ạ.o.d.a.n.h': 'mạo danh',
    't.ộ.i': 'tội',
    'p.h.ạ.m': 'phạm',
    'c.ờ.b.ạ.c': 'cờ bạc',
    'n.g.h.i.ệ.n': 'nghiện',
    'c.á.đ.ộ': 'cá độ',
    'm.ạ.i.d.â.m': 'mại dâm',
    # Bệnh tật, thương tích
    'm.á.u': 'máu',
    'v.ế.t': 'vết',
    't.h.ư.ơ.n.g': 'thương',
    't.h.ư.ơ.n.g.t.í.c.h': 'thương tích',
    'b.ệ.n.h': 'bệnh',
    'ố.m': 'ốm',
    's.ố.t': 'sốt',
    'h.o': 'ho',
    'c.ả.m': 'cảm',
    'n.h.i.ễ.m': 'nhiễm',
    'v.i.r.u.s': 'virus',
    'v.i.k.h.u.ẩ.n': 'vi khuẩn',
    'k.ý.s.i.n.h': 'ký sinh',
    't.r.ù.n.g': 'trùng',
    'đ.ộ.c': 'độc',
    'b.ỏ.n.g': 'bỏng',
    'g.ã.y': 'gãy',
    'r.á.c.h': 'rách',
    'c.h.ả.y': 'chảy',
    't.r.ầ.y': 'trầy',
    'b.ầ.m': 'bầm',
    's.ẹ.o': 'sẹo',
    # Chất kích thích
    'r.ư.ợ.u': 'rượu',
    'b.i.a': 'bia',
    't.h.u.ố.c': 'thuốc',
    'l.á': 'lá',
    'h.ú.t': 'hút',
    'h.í.t': 'hít',
    'n.g.ậ.m': 'ngậm',
    'n.h.a.i': 'nhai',
    'n.u.ố.t': 'nuốt',
    'u.ố.n.g': 'uống',
    'c.h.è': 'chè',
    'c.à.p.h.ê': 'cà phê',
    't.r.à': 'trà',
    # Tình dục, tục tĩu, xúc phạm
    't.ì.n.h': 'tình',
    'd.ụ.c': 'dục',
    'y.ê.u': 'yêu',
    'h.ô.n': 'hôn',
    'ô.m': 'ôm',
    'v.ỗ': 'vỗ',
    'v.u.ố.t': 'vuốt',
    's.ờ': 'sờ',
    'n.ự.n.g': 'nựng',
    'm.â.n': 'mân',
    'đ.ụ.c': 'đực',
    'c.á.i': 'cái',
    'đ.ị.t': 'địt',
    'c.ứ.t': 'cứt',
    'l.ồ.n': 'lồn',
    'c.ặ.c': 'cặc',
    'đ.ụ': 'đụ',
    'đ.ĩ': 'đĩ',
    'c.h.ó': 'chó',
    'm.ẹ': 'mẹ',
    't.h.ằ.n.g': 'thằng',
    'm.ấ.y': 'mày',
    't.ổ.s.ư': 'tổ sư',
    # Cảm xúc tiêu cực
    'g.h.é.t': 'ghét',
    'c.h.á.n': 'chán',
    't.ứ.c': 'tức',
    'g.i.ậ.n': 'giận',
    'c.ă.n.g': 'căng',
    's.ợ': 'sợ',
    'h.ã.i': 'hãi',
    'k.h.ủ.n.g': 'khủng',
    'h.o.ả.n.g': 'hoảng',
    'l.o.ạ.n': 'loạn',
    'r.ố.i': 'rối',
    'b.ứ.c': 'bức',
    'b.ự.c': 'bực',
    's.t.r.e.s.s': 'stress',
    't.r.ầ.m': 'trầm',
    'u.ấ.t': 'uất',
    'h.ậ.n': 'hận',
    # Bộ phận cơ thể (có thể nhạy cảm)
    'm.ặ.t': 'mặt',
    'm.ũ.i': 'mũi',
    'm.ồ.m': 'mồm',
    'm.á': 'má',
    't.a.y': 'tay',
    'c.h.â.n': 'chân',
    'b.ụ.n.g': 'bụng',
    'l.ư.n.g': 'lưng',
    'c.ổ': 'cổ',
    'đ.ầ.u': 'đầu',
    't.i.m': 'tim',
    'p.h.ổ.i': 'phổi',
    'g.a.n': 'gan',
    't.h.ậ.n': 'thận',
    'd.ạ.d.à.y': 'dạ dày',
    'r.ă.n.g': 'răng',
    'l.ư.ỡ.i': 'lưỡi',
    't.a.i': 'tai',
    'm.ắ.t': 'mắt',
    # Chính trị, tôn giáo (cân nhắc sử dụng)
    'c.ộ.n.g.s.ả.n': 'cộng sản',
    'p.h.ả.n.đ.ộ.n.g': 'phản động',
    'c.h.í.n.h.t.r.ị': 'chính trị',
    't.ô.n.g.i.á.o': 'tôn giáo',
    'p.h.ậ.t': 'phật',
    'c.h.ú.a': 'chúa',
    'h.ồ.c.h.í.m.i.n.h': 'hồ chí minh',
    'đ.ả.n.g': 'đảng',
    'c.h.í.n.h.p.h.ủ': 'chính phủ',
    'q.u.ố.c.h.ộ.i': 'quốc hội',
    'b.ộ.t.r.ư.ở.n.g': 'bộ trưởng',
    't.ổ.n.g.t.h.ố.n.g': 'tổng thống',
    'c.h.ủ.t.ị.c.h': 'chủ tịch'
}
sensitive_words.update({
    'd.a.o': 'dao',
    's.ú.n.g': 'súng',
    'k.é.o': 'kéo',
    'g.ậ.y': 'gậy',
    'r.ì.u': 'rìu',
    'k.i.ế.m': 'kiếm',
    'l.ư.ỡ.i.l.ê': 'lưỡi lê',
    'b.ú.a': 'búa',
    'c.h.ù.y': 'chùy',
    'n.ỏ': 'nỏ',
    'm.ã.t.t.r.ư.ớ.c': 'mã tấu',
    'l.ự.u.đ.ạ.n': 'lựu đạn',
    'b.o.m': 'bom',
    'm.í.n': 'mìn',
    'c.u.n.g': 'cung',
    't.ê.n': 'tên',
    'g.â.y.g.ộ.c': 'gậy gộc',
    'c.h.ù.m': 'chùm',
    'l.ư.ỡ.i.h.á.i': 'lưỡi hái',
    'x.à.b.e.n': 'xà beng',
    'c.à.l.ê': 'cà lê',
    't.u.a.v.i.t': 'tuavit',
    'b.ấ.m.đ.ạ.n': 'bấm đạn',
    'd.â.y.t.h.é.p': 'dây thép',
    'c.ư.a.l.ớ.n': 'cưa lớn',
    'g.ậ.y.b.a.s.ô.n.g': 'gậy ba sông',
    'g.ậ.y.đ.i.ệ.n': 'gậy điện',
    'b.ì.n.h.x.ị.t': 'bình xịt',
    'b.ì.n.h.x.ì.n.h': 'bình xình',
    'l.ư.ỡ.i.c.ư.a': 'lưỡi cưa',
    'c.h.ù.y.s.ắ.t': 'chùy sắt'
})
sensitive_words.update({
    'm.a': 'ma',
    'q.u.ỷ': 'quỷ',
    'v.o.n.g': 'vong',
    'h.ồ.n': 'hồn',
    'l.i.n.h.h.ồ.n': 'linh hồn',
    't.h.ầ.n': 'thần',
    't.h.á.n.h': 'thánh',
    'b.ù.a': 'bùa',
    'n.g.ả.i': 'ngải',
    't.h.ầ.y.b.ù.a': 'thầy bùa',
    't.h.ầ.y.p.h.á.p': 'thầy pháp',
    't.h.ầ.y.c.h.ú.a': 'thầy chùa',
    't.h.ầ.y.c.h.ủ.a': 'thầy chửa',
    'c.ầ.u.h.ồ.n': 'cầu hồn',
    'c.ầ.u.c.h.ú': 'cầu chú',
    'c.ầ.u.m.a.y': 'cầu may',
    'x.e.m.b.ó.i': 'xem bói',
    'b.ó.i.t.o.á.n': 'bói toán',
    'b.ó.i.b.a.i': 'bói bài',
    'b.ó.i.c.h.ỉ': 'bói chỉ',
    'b.ó.i.t.ơ.i': 'bói tơ i',
    'l.ê.n.đ.ồ.n.g': 'lên đồng',
    'n.h.ậ.p.x.á.c': 'nhập xác',
    't.r.ừ.t.à': 'trừ tà',
    't.r.ừ.q.u.ỷ': 'trừ quỷ',
    'g.ọ.i.h.ồ.n': 'gọi hồn',
    'g.ọ.i.v.o.n.g': 'gọi vong',
    'c.h.ú.n.g.t.a.i': 'chúng ta i',
    'c.h.ú.n.g.t.a.i.m.a': 'chúng ta i ma',
    'c.h.ú.n.g.t.a.i.q.u.ỷ': 'chúng ta i quỷ',
    'c.h.ú.n.g.t.a.i.t.h.ầ.n': 'chúng ta i thần',
    'c.h.ú.n.g.t.a.i.t.h.á.n.h': 'chúng ta i thánh'
})

sensitive_words.update({
    's.á.t.h.ạ.i': 'sát hại',
    'c.ư.ớ.p.g.i.ế.t': 'cướp giết',
    'x.ả.s.ú.n.g': 'xả súng',
    'c.h.ặ.t.đ.ầ.u': 'chặt đầu',
    'c.ắ.t.c.ổ': 'cắt cổ',
    'c.h.é.m.g.i.ế.t': 'chém giết',
    'b.ạ.o.l.ự.c': 'bạo lực',
    'k.ẻ.s.á.t.n.h.â.n': 'kẻ sát nhân',
    'đ.â.m.c.h.ế.t': 'đâm chết',
    'đ.ầ.u.g.ấ.u': 'đầu gấu',
    'c.h.ơ.i.đ.ề': 'chơi đề',
    'c.h.ơ.i.b.ạ.c': 'chơi bạc',
    'b.ă.n.g.đ.ả.n.g': 'băng đảng',
    'h.ù.d.ọ.a': 'hù dọa',
    'c.h.ố.n.g.đ.ố.i': 'chống đối',
    'c.h.ố.n.g.n.g.h.ị': 'chống nghị',
    'b.ấ.t.ô.n': 'bất ổn',
    'h.à.n.h.h.ạ': 'hành hạ',
    'm.ấ.t.k.i.ể.m.s.o.á.t': 'mất kiểm soát',
    'm.ấ.t.n.g.u.y.ệ.n': 'mất nguyên',
    'm.a.t.ú.y': 'ma túy',
    'm.a.t.ú.y.đ.á': 'ma túy đá',
    'm.a.t.ú.y.t.ổ.n.g.h.ợ.p': 'ma túy tổng hợp',
    'h.à.n.h': 'hành',
    'b.ó.c.p.h.ố.t': 'bóc phốt',
    'c.h.ử.i.t.h.ề': 'chửi thề',
    'l.ă.n': 'lằn',
    't.h.ề': 'thề',
    'c.ấ.u.k.ị.c.h': 'cấu kích',
    't.h.a.n.h.t.ẩ.u': 'thanh tẩu',
    'd.i.ậ.u.h.ộ': 'diệu hộ',
    'm.a.c.h.ó.n': 'ma chôn',
    'đ.ồ.n.g.c.ô': 'đồng cô',
    'đ.ồ.n.g.b.ó.n.g': 'đồng bóng',
})
sensitive_words.update({
    # Bạo lực, động chạm
    'đâm': 'đâm',
    'đ.â.m': 'đâm',
    'chém': 'chém',
    'sờ': 'sờ',
    'mó': 'mó',
    'nựng': 'nựng',
    'vịn': 'vịn',
    'ôm': 'ôm',
    'vuốt': 'vuốt',
    'hôn': 'hôn',
    'tát': 'tát',
    'bóp': 'bóp',
    'vỗ': 'vỗ',
    'cắn': 'cắn',
})

sensitive_words.update({
    'v.ú': 'vú',
    'b.ú': 'bú',
    'n.ú': 'nú',
    'n.ú.m.ú': 'nú mú',
    'n.ú.v.ú': 'nú vú',
    'd.ư.ơ.n.g.v.ậ.t': 'dương vật',
    'c.ơ.q.u.a.n.s.i.n.h.d.ụ.c.n.a.m': 'cơ quan sinh dục nam',
    'c.ơ.q.u.a.n.s.i.n.h.d.ụ.c.n.ữ': 'cơ quan sinh dục nữ',
    'â.m.v.ậ.t': 'âm vật',
    'â.m.đ.ạ.o': 'âm đạo',
    'h.ậ.u.m.ô.n': 'hậu môn',
    'n.g.ự.c': 'ngực',
    'n.g.ự.c.t.r.ầ.n': 'ngực trần',
    'n.ú.t.i.': 'nú ti',
    'n.g.ự.c.l.ớ.n': 'ngực lớn',
    'b.ì.m': 'bìm',
    'l.ô.n': 'lồn',
    'l.ô.n.l.ớ.n': 'lồn lớn',
    'c.ặ.c': 'cặc',
    'd.á.i': 'dái',
    't.i.': 'ti',
    't.i.h.õ.n': 'ti nhỏ',
    't.i.t.o': 'ti to',
    'c.h.ì.m': 'chìm/chym',
    'c.h.ũ.m': 'chũm (biến thể của chùm)',
})
# đoạn này tự tổng hợp
tonghop = {
    'đ.â.m': "đâm",
    'c.h.ế.t': 'chết',
    'g.i.ế.t': 'giết',
    'c.h.é.m': 'chém',
    'đ.á.n.h': 'đánh',
    'đ.ấ.m': 'đấm',
    'b.ắ.n': 'bắn',
    't.á.t': 'tát',
    't.r.ó.i': 'trói',
    'b.ó.p': 'bóp',
    'b.ó': 'bó',
    'đ.ố.t': 'đốt',
    'p.h.á': 'phá',
    'n.ổ': 'nổ',
    
}
def fix_by_dict(text):
    """
    Chuyển đổi các từ nhạy cảm về dạng bình thường
    """
    for sensitive, normal in sensitive_words.items():
        text = text.replace(sensitive, normal)
    return text

from re import findall

def fix_by_regex(text):
    """
    Sử dụng regex để tìm ra các từ như đ.â.m -> đâm 
    """
    pattern = r'\b(?:[a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]\.)+[a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ]\b'
    matches = findall(pattern, text)
    if not matches:
        return text
    else:
        for match in list(dict.fromkeys(matches)):
            match_fix = match.replace('.', '')
            text = text.replace(match, match_fix)
        return text
